<?php

/**
 * @file
 * Main functions and template preprocessor.
 */

use Drupal\Core\Template\Attribute;
use Drupal\Core\Url;

/**
 * Implements hook_libraries_info().
 */
function openseadragon_libraries_info() {
  $libraries['openseadragon'] = [
    'name' => 'OpenSeadragon plugin',
    'vendor url' => 'https://openseadragon.github.io/',
    'download url' => 'https://github.com/openseadragon/openseadragon/master/zipball',
    'version arguments' => [
      'file' => 'openseadragon.js',
      // //! openseadragon 2.2.1.
      'pattern' => '@openseadragon ([0-9\.-]+)@',
      'lines' => 1,
      'columns' => 50,
    ],
    'versions' => [
      '2.2.1' => [
        'files' => [
          'js' => [
            'openseadragon.js',
          ],
        ],
      ],
    ],
  ];
  return $libraries;
}

/**
 * Implements hook_theme().
 */
function openseadragon_theme() {
  return [
    'openseadragon_formatter' => [
      'variables' => [
        'item' => NULL,
        'entity' => NULL,
        'settings' => NULL,
      ],
    ],
  ];
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_openseadragon_formatter(&$variables) {
  $item = $variables['item'];
  $entity = $variables['entity'];
  // Load the global settings.
  $config = \Drupal::service('openseadragon.config');
  $fileinfo_service = \Drupal::service('openseadragon.fileinfo');

  // TODO: Once Libraries API is finished find a function for this.
  $base_library_path = 'sites/all/assets/vendor';

  // Build the gallery id.
  $id = $entity->id();
  $openseadragon_viewer_id = 'openseadragon-viewer-' . $id;
  $field_name = $item->getParent()->getName();

  $resource = $fileinfo_service->getFileData($field_name, $entity);

  $classes_array = ['openseadragon-viewer'];
  $viewer_settings = $config->getSettings(TRUE);
  $iiif_address = $config->getIiifAddress();

  if (!is_null($iiif_address) && !empty($iiif_address)) {
    // Strip the root off to get the relative to root file path.
    $full_path = str_replace(DRUPAL_ROOT . '/', '', $resource['full_path']);

    $tile_source = rtrim($iiif_address, '/') . '/' . urlencode($full_path);

    $variables['#attached']['drupalSettings']['openseadragon'] = [
      'basePath' => Url::fromUri($iiif_address),
      'fitToAspectRatio' => $viewer_settings['fit_to_aspect_ratio'],
      'options' => [
        'id' => $openseadragon_viewer_id,
        'prefixUrl' => file_create_url("{$base_library_path}/openseadragon/images/"),
        'tileSources' => $tile_source,
      ] + $viewer_settings,
    ];

    $variables['attributes'] = new Attribute();
    $variables['attributes']['class'] = $classes_array;
    $variables['attributes']['id'] = $openseadragon_viewer_id;
  }
}
