<?php

/**
 * @file
 * Attach bookmark-url.js.
 */

/**
 * Attach openseadragon_bookmark_url js if openseadragon_formatter used.
 *
 * Implements hook_preprocess_HOOK().
 *
 * {@inheritDoc}
 */
function openseadragon_bookmark_url_preprocess_field(&$variables) {
  if (isset($variables['items'])) {
    foreach ($variables['items'] as $item) {
      if (isset($item['content']['#theme']) && $item['content']['#theme'] == 'openseadragon_formatter') {
        $variables['#attached']['library'][] = 'openseadragon_bookmark_url/openseadragon_bookmark_url';

        // Inject bookmark URL into settings for later reference in js.
        $config = \Drupal::config('openseadragon_bookmark_url.settings');
        $bookmark_url_bundle = $config->get('bookmark_url_bundle');
        $bookmark_url_field = $config->get('bookmark_url_field');
        if (isset($item['content']['#entity'])) {
          $entity = $item['content']['#entity'];
          if ($entity->bundle() == $bookmark_url_bundle) {
            $openseadragon_viewer_id = 'openseadragon-viewer-' . $entity->id();
            if ($entity->hasField($bookmark_url_field)) {
              $fragment = $entity->get($bookmark_url_field)->value;
              $variables['#attached']['drupalSettings']['openseadragon'][$openseadragon_viewer_id]['openseadragonBookmarkUrl'] = $fragment;
            }
          }
        }
      }
    }
  }
}
